version: '2'
services:
  # after docker-compose.yml services startup,
  # then create another service to validate service discovery
  organizationservice3:
    image: denglitong/organization-service:chapter4
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configurationservice:8888"
      EUREKASERVER_URI: "http://eurekaservice:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
